version: '3.7'

services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 1323:1323
    depends_on:
      - "mysql"

  mysql:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: 232323
      MYSQL_DATABASE: hokku
    command: 
      mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - "./migrations/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./migrations/test_data.sql:/docker-entrypoint-initdb.d/2.sql"