version: '3.8'

services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 1323:1323

  mysql:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: 232323
      MYSQL_DATABASE: hokku
    volumes:
      - "./migrations/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./migrations/test_data.sql:/docker-entrypoint-initdb.d/2.sql"